# Generated by Django 4.1 on 2022-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="start_date",
        ),
        migrations.AddField(
            model_name="user",
            name="cellphone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="input_company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
